# https://hub.docker.com/r/canal/canal-server

services:
  canal-cluster-node1:
    image: ${CANAL_IMAGE}
    container_name: canal-cluster-node1
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - canal.register.ip=${CANAL_CLUSTER_NODE1_REGISTER_IP}
      - canal.port=${CANAL_CLUSTER_NODE1_PORT_11111}
      - canal.metrics.pull.port=${CANAL_CLUSTER_NODE1_PORT_11112}
      - canal.admin.port=${CANAL_CLUSTER_NODE1_PORT_11110}
      - canal.admin.manager=${CANAL_ADMIN_MANAGER}
      - canal.admin.user=${CANAL_ADMIN_USER}
      - canal.admin.passwd=${CANAL_ADMIN_PASSWD}
      - canal.admin.register.cluster=${CANAL_CLUSTER_NAME}
      - canal.zkServers=${CANAL_CLUSTER_ZKSERVERS}
    volumes:
      - ${CANAL_CLUSTER_HOME}/node1/logs:/home/admin/canal-server/logs
    networks:
      - zookeeper
      - canal_admin
      - canal_cluster
    ports:
      - ${CANAL_CLUSTER_NODE1_PORT_11110}:${CANAL_CLUSTER_NODE1_PORT_11110}
      - ${CANAL_CLUSTER_NODE1_PORT_11111}:${CANAL_CLUSTER_NODE1_PORT_11111}
      - ${CANAL_CLUSTER_NODE1_PORT_11112}:${CANAL_CLUSTER_NODE1_PORT_11112}
  canal-cluster-node2:
    image: ${CANAL_IMAGE}
    container_name: canal-cluster-node2
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - canal.register.ip=${CANAL_CLUSTER_NODE2_REGISTER_IP}
      - canal.port=${CANAL_CLUSTER_NODE2_PORT_11111}
      - canal.metrics.pull.port=${CANAL_CLUSTER_NODE2_PORT_11112}
      - canal.admin.port=${CANAL_CLUSTER_NODE2_PORT_11110}
      - canal.admin.manager=${CANAL_ADMIN_MANAGER}
      - canal.admin.user=${CANAL_ADMIN_USER}
      - canal.admin.passwd=${CANAL_ADMIN_PASSWD}
      - canal.admin.register.cluster=${CANAL_CLUSTER_NAME}
      - canal.zkServers=${CANAL_CLUSTER_ZKSERVERS}
    volumes:
      - ${CANAL_CLUSTER_HOME}/node2/logs:/home/admin/canal-server/logs
    networks:
      - zookeeper
      - canal_admin
      - canal_cluster
    ports:
      - ${CANAL_CLUSTER_NODE2_PORT_11110}:${CANAL_CLUSTER_NODE2_PORT_11110}
      - ${CANAL_CLUSTER_NODE2_PORT_11111}:${CANAL_CLUSTER_NODE2_PORT_11111}
      - ${CANAL_CLUSTER_NODE2_PORT_11112}:${CANAL_CLUSTER_NODE2_PORT_11112}
  canal-cluster-node3:
    image: ${CANAL_IMAGE}
    container_name: canal-cluster-node3
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - canal.register.ip=${CANAL_CLUSTER_NODE3_REGISTER_IP}
      - canal.port=${CANAL_CLUSTER_NODE3_PORT_11111}
      - canal.metrics.pull.port=${CANAL_CLUSTER_NODE3_PORT_11112}
      - canal.admin.port=${CANAL_CLUSTER_NODE3_PORT_11110}
      - canal.admin.manager=${CANAL_ADMIN_MANAGER}
      - canal.admin.user=${CANAL_ADMIN_USER}
      - canal.admin.passwd=${CANAL_ADMIN_PASSWD}
      - canal.admin.register.cluster=${CANAL_CLUSTER_NAME}
      - canal.zkServers=${CANAL_CLUSTER_ZKSERVERS}
    volumes:
      - ${CANAL_CLUSTER_HOME}/node3/logs:/home/admin/canal-server/logs
    networks:
      - zookeeper
      - canal_admin
      - canal_cluster
    ports:
      - ${CANAL_CLUSTER_NODE3_PORT_11110}:${CANAL_CLUSTER_NODE3_PORT_11110}
      - ${CANAL_CLUSTER_NODE3_PORT_11111}:${CANAL_CLUSTER_NODE3_PORT_11111}
      - ${CANAL_CLUSTER_NODE3_PORT_11112}:${CANAL_CLUSTER_NODE3_PORT_11112}
networks:
  canal_cluster:
    driver: bridge
  canal_admin:
    external:
      name: ${CANAL_ADMIN_SERVICE_NETWORK}
  zookeeper:
    external:
      name: ${CANAL_CLUSTER_ZKSERVERS_NETWORK}