# https://hub.docker.com/r/bitnami/rabbitmq

services:
  rabbitmq:
    image: ${RABBITMQ_IMAGE}
    container_name: rabbitmq
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_NODE_TYPE
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
      - RABBITMQ_PLUGINS
      - RABBITMQ_COMMUNITY_PLUGINS
    volumes:
      - ${RABBITMQ_HOME}/:/bitnami/rabbitmq
      - ${RABBITMQ_HOME}/conf/custom.conf:/bitnami/rabbitmq/conf/custom.conf:ro
    networks:
      - rabbitmq
    ports:
      - ${RABBITMQ_PORT_5671}:5671
      - ${RABBITMQ_PORT_5672}:5672
      - ${RABBITMQ_PORT_15672}:15672
networks:
  rabbitmq:
    driver: bridge