# https://hub.docker.com/r/seataio/seata-server

services:
  seata-cluster-node1:
    image: ${SEATA_IMAGE}
    container_name: seata-cluster-node1
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - SEATA_IP=${SEATA_CLUSTER_NODE1_HOST}
      - SEATA_PORT=${SEATA_CLUSTER_NODE1_PORT_8091}
    volumes:
      - ${SEATA_CLUSTER_HOME}/node1/logs:/root/logs
      - ${SEATA_CLUSTER_HOME}/node1/application.yml:/seata-server/resources/application.yml
    networks:
      - mysql
      - nacos
      - seata_cluster
    ports:
      - ${SEATA_CLUSTER_NODE1_PORT_7091}:7091
      - ${SEATA_CLUSTER_NODE1_PORT_8091}:${SEATA_CLUSTER_NODE1_PORT_8091}
    healthcheck:
      test: curl -f http://localhost:7091/
      interval: 5s
  seata-cluster-node2:
    image: ${SEATA_IMAGE}
    container_name: seata-cluster-node2
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - SEATA_IP=${SEATA_CLUSTER_NODE2_HOST}
      - SEATA_PORT=${SEATA_CLUSTER_NODE2_PORT_8091}
    volumes:
      - ${SEATA_CLUSTER_HOME}/node2/logs:/root/logs
      - ${SEATA_CLUSTER_HOME}/node2/application.yml:/seata-server/resources/application.yml
    networks:
      - mysql
      - nacos
      - seata_cluster
    ports:
      - ${SEATA_CLUSTER_NODE2_PORT_7091}:7091
      - ${SEATA_CLUSTER_NODE2_PORT_8091}:${SEATA_CLUSTER_NODE2_PORT_8091}
    healthcheck:
      test: curl -f http://localhost:7091/
      interval: 5s
  seata-cluster-node3:
    image: ${SEATA_IMAGE}
    container_name: seata-cluster-node3
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - SEATA_IP=${SEATA_CLUSTER_NODE3_HOST}
      - SEATA_PORT=${SEATA_CLUSTER_NODE3_PORT_8091}
    volumes:
      - ${SEATA_CLUSTER_HOME}/node3/logs:/root/logs
      - ${SEATA_CLUSTER_HOME}/node3/application.yml:/seata-server/resources/application.yml
    networks:
      - mysql
      - nacos
      - seata_cluster
    ports:
      - ${SEATA_CLUSTER_NODE3_PORT_7091}:7091
      - ${SEATA_CLUSTER_NODE3_PORT_8091}:${SEATA_CLUSTER_NODE3_PORT_8091}
    healthcheck:
      test: curl -f http://localhost:7091/
      interval: 5s
networks:
  seata_cluster:
    driver: bridge
  nacos:
    external:
      name: ${SEATA_NACOS_SERVICE_NETWORK}
  mysql:
    external:
      name: ${SEATA_MYSQL_SERVICE_NETWORK}