# https://hub.docker.com/r/seataio/seata-server

services:
  seata:
    image: ${SEATA_IMAGE}
    container_name: seata
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${SEATA_HOME}/logs:/root/logs
    networks:
      - seata_default
    ports:
      - ${SEATA_DEFAULT_PORT_7091}:7091
      - ${SEATA_DEFAULT_PORT_8091}:8091
    healthcheck:
      test: curl -f http://localhost:7091/
      interval: 5s
networks:
  seata_default:
    driver: bridge