# https://hub.docker.com/r/seataio/seata-server

services:
  seata:
    image: ${SEATA_IMAGE}
    container_name: seata
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - SEATA_IP=${SEATA_HOST}
      - SEATA_PORT=${SEATA_PORT_8091}
    volumes:
      - ${SEATA_HOME}/logs:/root/logs
      - ${SEATA_HOME}/application.yml:/seata-server/resources/application.yml
    networks:
      - mysql
      - nacos
      - seata
    ports:
      - ${SEATA_PORT_7091}:7091
      - ${SEATA_PORT_8091}:8091
    healthcheck:
      test: curl -f http://localhost:7091/
      interval: 5s
networks:
  seata:
    driver: bridge
  nacos:
    external:
      name: ${SEATA_NACOS_SERVICE_NETWORK}
  mysql:
    external:
      name: ${SEATA_MYSQL_SERVICE_NETWORK}