# https://hub.docker.com/r/seataio/seata-server

services:
  seata:
    image: ${SEATA_IMAGE}
    container_name: seata
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SEATA_PORT=${SEATA_DEFAULT_PORT_8091}
    ports:
      - ${SEATA_DEFAULT_PORT_8091}:8091
networks:
  seata_default:
    driver: bridge