# https://hub.docker.com/r/seataio/seata-server

services:
  seata:
    image: ${SEATA_IMAGE}
    container_name: seata
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${SEATA_HOME}/logs:/root/logs
      - ${SEATA_HOME}/application.yml:/seata-server/resources/application.yml
    networks:
      - mysql
      - seata_db_only
    ports:
      - ${SEATA_DB_ONLY_PORT_7091}:7091
      - ${SEATA_DB_ONLY_PORT_8091}:8091
    healthcheck:
      test: curl -f http://localhost:7091/
      interval: 5s
networks:
  seata_db_only:
    driver: bridge
  mysql:
    external:
      name: ${SEATA_MYSQL_SERVICE_NETWORK}