# https://hub.docker.com/r/bitnami/elasticsearch

services:
  elasticsearch-node1:
    image: ${ELASTICSEARCH_IMAGE}
    container_name: elasticsearch-node1
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HEAP_SIZE
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node1
      - ELASTICSEARCH_ADVERTISED_HOSTNAME=${ELASTICSEARCH_CLUSTER_NODE1_HOSTNAME}
      - ELASTICSEARCH_HTTP_PORT_NUMBER=${ELASTICSEARCH_CLUSTER_NODE1_PORT_9200}
      - ELASTICSEARCH_TRANSPORT_PORT_NUMBER=${ELASTICSEARCH_CLUSTER_NODE1_PORT_9300}
      - ELASTICSEARCH_CLUSTER_HOSTS=${ELASTICSEARCH_CLUSTER_NODE1_HOSTNAME}:${ELASTICSEARCH_CLUSTER_NODE1_PORT_9300},${ELASTICSEARCH_CLUSTER_NODE2_HOSTNAME}:${ELASTICSEARCH_CLUSTER_NODE2_PORT_9300},${ELASTICSEARCH_CLUSTER_NODE3_HOSTNAME}:${ELASTICSEARCH_CLUSTER_NODE3_PORT_9300}
      - ELASTICSEARCH_CLUSTER_MASTER_HOSTS=${ELASTICSEARCH_CLUSTER_NODE1_HOSTNAME},${ELASTICSEARCH_CLUSTER_NODE2_HOSTNAME},${ELASTICSEARCH_CLUSTER_NODE3_HOSTNAME}
    volumes:
      - ${ELASTICSEARCH_CLUSTER_HOME}/node1:/bitnami/elasticsearch/
      - ${ELASTICSEARCH_CLUSTER_HOME}/node1/plugins:/bitnami/elasticsearch/plugins
      - ${ELASTICSEARCH_CLUSTER_HOME}/node1/certs:/opt/bitnami/elasticsearch/config/certs
      - ${ELASTICSEARCH_CLUSTER_HOME}/node1/config/elasticsearch.yml:/opt/bitnami/elasticsearch/config/my_elasticsearch.yml
    networks:
      - elasticsearch_cluster
    ports:
      - ${ELASTICSEARCH_CLUSTER_NODE1_PORT_9200}:${ELASTICSEARCH_CLUSTER_NODE1_PORT_9200}
      - ${ELASTICSEARCH_CLUSTER_NODE1_PORT_9300}:${ELASTICSEARCH_CLUSTER_NODE1_PORT_9300}
  elasticsearch-node2:
    image: ${ELASTICSEARCH_IMAGE}
    container_name: elasticsearch-node2
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HEAP_SIZE
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node2
      - ELASTICSEARCH_ADVERTISED_HOSTNAME=${ELASTICSEARCH_CLUSTER_NODE2_HOSTNAME}
      - ELASTICSEARCH_HTTP_PORT_NUMBER=${ELASTICSEARCH_CLUSTER_NODE2_PORT_9200}
      - ELASTICSEARCH_TRANSPORT_PORT_NUMBER=${ELASTICSEARCH_CLUSTER_NODE2_PORT_9300}
      - ELASTICSEARCH_CLUSTER_HOSTS=${ELASTICSEARCH_CLUSTER_NODE1_HOSTNAME}:${ELASTICSEARCH_CLUSTER_NODE1_PORT_9300},${ELASTICSEARCH_CLUSTER_NODE2_HOSTNAME}:${ELASTICSEARCH_CLUSTER_NODE2_PORT_9300},${ELASTICSEARCH_CLUSTER_NODE3_HOSTNAME}:${ELASTICSEARCH_CLUSTER_NODE3_PORT_9300}
      - ELASTICSEARCH_CLUSTER_MASTER_HOSTS=${ELASTICSEARCH_CLUSTER_NODE1_HOSTNAME},${ELASTICSEARCH_CLUSTER_NODE2_HOSTNAME},${ELASTICSEARCH_CLUSTER_NODE3_HOSTNAME}
    volumes:
      - ${ELASTICSEARCH_CLUSTER_HOME}/node2:/bitnami/elasticsearch/
      - ${ELASTICSEARCH_CLUSTER_HOME}/node2/plugins:/bitnami/elasticsearch/plugins
      - ${ELASTICSEARCH_CLUSTER_HOME}/node2/certs:/opt/bitnami/elasticsearch/config/certs
      - ${ELASTICSEARCH_CLUSTER_HOME}/node2/config/elasticsearch.yml:/opt/bitnami/elasticsearch/config/my_elasticsearch.yml
    networks:
      - elasticsearch_cluster
    ports:
      - ${ELASTICSEARCH_CLUSTER_NODE2_PORT_9200}:${ELASTICSEARCH_CLUSTER_NODE2_PORT_9200}
      - ${ELASTICSEARCH_CLUSTER_NODE2_PORT_9300}:${ELASTICSEARCH_CLUSTER_NODE2_PORT_9300}
  elasticsearch-node3:
    image: ${ELASTICSEARCH_IMAGE}
    container_name: elasticsearch-node3
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HEAP_SIZE
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node3
      - ELASTICSEARCH_ADVERTISED_HOSTNAME=${ELASTICSEARCH_CLUSTER_NODE3_HOSTNAME}
      - ELASTICSEARCH_HTTP_PORT_NUMBER=${ELASTICSEARCH_CLUSTER_NODE3_PORT_9200}
      - ELASTICSEARCH_TRANSPORT_PORT_NUMBER=${ELASTICSEARCH_CLUSTER_NODE3_PORT_9300}
      - ELASTICSEARCH_CLUSTER_HOSTS=${ELASTICSEARCH_CLUSTER_NODE1_HOSTNAME}:${ELASTICSEARCH_CLUSTER_NODE1_PORT_9300},${ELASTICSEARCH_CLUSTER_NODE2_HOSTNAME}:${ELASTICSEARCH_CLUSTER_NODE2_PORT_9300},${ELASTICSEARCH_CLUSTER_NODE3_HOSTNAME}:${ELASTICSEARCH_CLUSTER_NODE3_PORT_9300}
      - ELASTICSEARCH_CLUSTER_MASTER_HOSTS=${ELASTICSEARCH_CLUSTER_NODE1_HOSTNAME},${ELASTICSEARCH_CLUSTER_NODE2_HOSTNAME},${ELASTICSEARCH_CLUSTER_NODE3_HOSTNAME}
    volumes:
      - ${ELASTICSEARCH_CLUSTER_HOME}/node3:/bitnami/elasticsearch/
      - ${ELASTICSEARCH_CLUSTER_HOME}/node3/plugins:/bitnami/elasticsearch/plugins
      - ${ELASTICSEARCH_CLUSTER_HOME}/node3/certs:/opt/bitnami/elasticsearch/config/certs
      - ${ELASTICSEARCH_CLUSTER_HOME}/node3/config/elasticsearch.yml:/opt/bitnami/elasticsearch/config/my_elasticsearch.yml
    networks:
      - elasticsearch_cluster
    ports:
      - ${ELASTICSEARCH_CLUSTER_NODE3_PORT_9200}:${ELASTICSEARCH_CLUSTER_NODE3_PORT_9200}
      - ${ELASTICSEARCH_CLUSTER_NODE3_PORT_9300}:${ELASTICSEARCH_CLUSTER_NODE3_PORT_9300}
networks:
  elasticsearch_cluster:
    driver: bridge