# https://hub.docker.com/r/bitnami/elasticsearch

services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    container_name: elasticsearch
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HEAP_SIZE
    volumes:
      - ${ELASTICSEARCH_HOME}/:/bitnami/elasticsearch/
      - ${ELASTICSEARCH_HOME}/plugins:/bitnami/elasticsearch/plugins
      - ${ELASTICSEARCH_HOME}/certs:/opt/bitnami/elasticsearch/config/certs
      - ${ELASTICSEARCH_HOME}/config/elasticsearch.yml:/opt/bitnami/elasticsearch/config/my_elasticsearch.yml
    networks:
      - elasticsearch
    ports:
      - ${ELASTICSEARCH_PORT_9200}:9200
      - ${ELASTICSEARCH_PORT_9300}:9300
networks:
  elasticsearch:
    driver: bridge