# https://hub.docker.com/r/nacos/nacos-server

services:
  nacos-cluster-node1:
    image: ${NACOS_IMAGE}
    container_name: nacos-cluster-node1
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - MODE=cluster
      - NACOS_SERVERS=nacos-cluster-node2 nacos-cluster-node3
      - TZ=Asia/Shanghai
      - JVM_XMS=${NACOS_JVM_XMS}
      - JVM_XMX=${NACOS_JVM_XMX}
      - NACOS_AUTH_ENABLE=${NACOS_AUTH_ENABLE}
      - NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN}
      - NACOS_AUTH_CACHE_ENABLE=${NACOS_AUTH_CACHE_ENABLE}
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE}
      - PREFER_HOST_MODE=${NACOS_PREFER_HOST_MODE}
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=${NACOS_MYSQL_SERVICE_HOST}
      - MYSQL_SERVICE_PORT=${NACOS_MYSQL_SERVICE_PORT}
      - MYSQL_SERVICE_USER=${NACOS_MYSQL_SERVICE_USER}
      - MYSQL_SERVICE_PASSWORD=${NACOS_MYSQL_SERVICE_PASSWORD}
      - MYSQL_SERVICE_DB_NAME=${NACOS_MYSQL_SERVICE_DB_NAME}
      - MYSQL_SERVICE_DB_PARAM=useUnicode=true&characterEncoding=utf8&connectTimeout=3000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    volumes:
      - ${NACOS_CLUSTER_HOME}/node1/logs:/home/nacos/logs
    networks:
      - mysql
      - nacos_cluster
    ports:
      - ${NACOS_CLUSTER_NODE1_PORT_7848}:7848
      - ${NACOS_CLUSTER_NODE1_PORT_8848}:8848
      - ${NACOS_CLUSTER_NODE1_PORT_9848}:9848
      - ${NACOS_CLUSTER_NODE1_PORT_9849}:9849
    healthcheck:
      test: curl -Ls http://localhost:8848/nacos/actuator/health | grep UP
      interval: 5s
  nacos-cluster-node2:
    image: ${NACOS_IMAGE}
    container_name: nacos-cluster-node2
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - MODE=cluster
      - NACOS_SERVERS=nacos-cluster-node1 nacos-cluster-node3
      - TZ=Asia/Shanghai
      - JVM_XMS=${NACOS_JVM_XMS}
      - JVM_XMX=${NACOS_JVM_XMX}
      - NACOS_AUTH_ENABLE=${NACOS_AUTH_ENABLE}
      - NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN}
      - NACOS_AUTH_CACHE_ENABLE=${NACOS_AUTH_CACHE_ENABLE}
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE}
      - PREFER_HOST_MODE=${NACOS_PREFER_HOST_MODE}
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=${NACOS_MYSQL_SERVICE_HOST}
      - MYSQL_SERVICE_PORT=${NACOS_MYSQL_SERVICE_PORT}
      - MYSQL_SERVICE_USER=${NACOS_MYSQL_SERVICE_USER}
      - MYSQL_SERVICE_PASSWORD=${NACOS_MYSQL_SERVICE_PASSWORD}
      - MYSQL_SERVICE_DB_NAME=${NACOS_MYSQL_SERVICE_DB_NAME}
      - MYSQL_SERVICE_DB_PARAM=useUnicode=true&characterEncoding=utf8&connectTimeout=3000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    volumes:
      - ${NACOS_CLUSTER_HOME}/node2/logs:/home/nacos/logs
    networks:
      - mysql
      - nacos_cluster
    ports:
      - ${NACOS_CLUSTER_NODE2_PORT_7848}:7848
      - ${NACOS_CLUSTER_NODE2_PORT_8848}:8848
      - ${NACOS_CLUSTER_NODE2_PORT_9848}:9848
      - ${NACOS_CLUSTER_NODE2_PORT_9849}:9849
    healthcheck:
      test: curl -Ls http://localhost:8848/nacos/actuator/health | grep UP
      interval: 5s
  nacos-cluster-node3:
    image: ${NACOS_IMAGE}
    container_name: nacos-cluster-node3
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - MODE=cluster
      - NACOS_SERVERS=nacos-cluster-node1 nacos-cluster-node2
      - TZ=Asia/Shanghai
      - JVM_XMS=${NACOS_JVM_XMS}
      - JVM_XMX=${NACOS_JVM_XMX}
      - NACOS_AUTH_ENABLE=${NACOS_AUTH_ENABLE}
      - NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN}
      - NACOS_AUTH_CACHE_ENABLE=${NACOS_AUTH_CACHE_ENABLE}
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE}
      - PREFER_HOST_MODE=${NACOS_PREFER_HOST_MODE}
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=${NACOS_MYSQL_SERVICE_HOST}
      - MYSQL_SERVICE_PORT=${NACOS_MYSQL_SERVICE_PORT}
      - MYSQL_SERVICE_USER=${NACOS_MYSQL_SERVICE_USER}
      - MYSQL_SERVICE_PASSWORD=${NACOS_MYSQL_SERVICE_PASSWORD}
      - MYSQL_SERVICE_DB_NAME=${NACOS_MYSQL_SERVICE_DB_NAME}
      - MYSQL_SERVICE_DB_PARAM=useUnicode=true&characterEncoding=utf8&connectTimeout=3000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    volumes:
      - ${NACOS_CLUSTER_HOME}/node3/logs:/home/nacos/logs
    networks:
      - mysql
      - nacos_cluster
    ports:
      - ${NACOS_CLUSTER_NODE3_PORT_7848}:7848
      - ${NACOS_CLUSTER_NODE3_PORT_8848}:8848
      - ${NACOS_CLUSTER_NODE3_PORT_9848}:9848
      - ${NACOS_CLUSTER_NODE3_PORT_9849}:9849
    healthcheck:
      test: curl -Ls http://localhost:8848/nacos/actuator/health | grep UP
      interval: 5s
networks:
  nacos_cluster:
    driver: bridge
  mysql:
    external:
      name: ${NACOS_MYSQL_SERVICE_NETWORK}