apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  userID: cephfs
  userKey: AQBt1QNjlAEDJRAAWFeUCwOTLRcfDuok2dvejA==
  adminID: admin
  adminKey: AQBAmgNjcKxwGxAANjoDA2L12Ap403+qjB4tCA==
