# https://hub.docker.com/r/bitnami/solr

services:
  solr-cluster-node1:
    image: ${SOLR_IMAGE}
    container_name: solr-cluster-node1
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SOLR_OPTS
      - SOLR_ADMIN_USERNAME
      - SOLR_ADMIN_PASSWORD
      - SOLR_ENABLE_AUTHENTICATION
      - SOLR_ENABLE_CLOUD_MODE=yes
      - SOLR_NUMBER_OF_NODES=1
      - SOLR_HOST=${SOLR_CLUSTER_NODE1_HOST}
      - SOLR_PORT_NUMBER=${SOLR_CLUSTER_NODE1_PORT_8983}
      - SOLR_ZK_HOSTS=${SOLR_CLUSTER_ZOO_SERVICE_HOSTS}
    volumes:
      - ${SOLR_CLUSTER_HOME}/node1:/bitnami/solr
    networks:
      - zookeeper
      - solr_cluster
    ports:
      - ${SOLR_CLUSTER_NODE1_PORT_8983}:${SOLR_CLUSTER_NODE1_PORT_8983}
  solr-cluster-node2:
    image: ${SOLR_IMAGE}
    container_name: solr-cluster-node2
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - SOLR_OPTS
      - SOLR_ADMIN_USERNAME
      - SOLR_ADMIN_PASSWORD
      - SOLR_ENABLE_AUTHENTICATION
      - SOLR_ENABLE_CLOUD_MODE=yes
      - SOLR_NUMBER_OF_NODES=2
      - SOLR_HOST=${SOLR_CLUSTER_NODE2_HOST}
      - SOLR_PORT_NUMBER=${SOLR_CLUSTER_NODE2_PORT_8983}
      - SOLR_ZK_HOSTS=${SOLR_CLUSTER_ZOO_SERVICE_HOSTS}
    volumes:
      - ${SOLR_CLUSTER_HOME}/node2:/bitnami/solr
    networks:
      - zookeeper
      - solr_cluster
    ports:
      - ${SOLR_CLUSTER_NODE2_PORT_8983}:${SOLR_CLUSTER_NODE2_PORT_8983}
  solr-cluster-node3:
    image: ${SOLR_IMAGE}
    container_name: solr-cluster-node3
    restart: always
    environment:
      - BITNAMI_DEBUG
      - TZ=Asia/Shanghai
      - SOLR_OPTS
      - SOLR_ADMIN_USERNAME
      - SOLR_ADMIN_PASSWORD
      - SOLR_ENABLE_AUTHENTICATION
      - SOLR_ENABLE_CLOUD_MODE=yes
      - SOLR_NUMBER_OF_NODES=3
      - SOLR_HOST=${SOLR_CLUSTER_NODE3_HOST}
      - SOLR_PORT_NUMBER=${SOLR_CLUSTER_NODE3_PORT_8983}
      - SOLR_ZK_HOSTS=${SOLR_CLUSTER_ZOO_SERVICE_HOSTS}
      - SOLR_CLOUD_BOOTSTRAP=yes
    volumes:
      - ${SOLR_CLUSTER_HOME}/node3:/bitnami/solr
    depends_on:
      - solr-cluster-node1
      - solr-cluster-node2
    networks:
      - zookeeper
      - solr_cluster
    ports:
      - ${SOLR_CLUSTER_NODE3_PORT_8983}:${SOLR_CLUSTER_NODE3_PORT_8983}
networks:
  solr_cluster:
    driver: bridge
  zookeeper:
    external:
      name: ${SOLR_CLUSTER_ZOO_SERVICE_NETWORK}
