# https://hub.docker.com/r/bitnami/minio

services:
  minio:
    image: ${MINIO_IMAGE}
    container_name: minio
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_HOME}/data:/data
      - ${MINIO_HOME}/certs:/certs
    networks:
      - minio
    ports:
      - ${MINIO_PORT_9000}:9000
      - ${MINIO_PORT_9001}:9001
networks:
  minio:
    driver: bridge